name: Release Builds
on: push
env:
  QT_VERSION: "v6.10.2"
  ZLIB_VERSION: "v1.3.1"
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu-22.04"
            CONFIGURE_EXTRAS: "-DFEATURE_xcb=ON -DINPUT_bundled_xcb_xinput=yes -DFEATURE_libudev=OFF"
          - os: "ubuntu-22.04"
            CONFIGURE_EXTRAS: "-DFEATURE_sanitize_thread=ON -DFEATURE_xcb=ON -DINPUT_bundled_xcb_xinput=yes -DFEATURE_libudev=OFF"
            BUILD_TAG: "_tsan"
          - os: "ubuntu-22.04-arm"
          - os: "macos-14"
          - os: "windows-2022"
          - os: "windows-11-arm"
    permissions:
      contents: write
    env:
      CONFIGURE_EXTRAS: ${{ matrix.CONFIGURE_EXTRAS }}
      BUILD_TAG: ${{ matrix.BUILD_TAG }}
    steps:
      - uses: spatial-model-editor/setup-ci@2026.03.27
        with:
          cache_id: ${{ matrix.BUILD_TAG }}
      - uses: actions/checkout@v6
      - name: Build script
        if: runner.os != 'Windows'
        run: ./build.sh
      - name: Build script
        if: runner.os == 'Windows'
        run: ./build.ps1
      - name: Upload binaries to release if commit is tagged
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artefacts/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
